Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: 'Provides basic EKS cluster permissions'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      RoleName: airflow-poc-eks-cluster-role
  NodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: 'Provides basic EKS node permissions'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSBatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      RoleName: airflow-poc-eks-node-role
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: "airflow-poc-cluster"
      ResourcesVpcConfig:
        SubnetIds:
          - "subnet-04e9d0c9f1940f570"
          - "subnet-0109e0d73006b4bc8"
          - "subnet-0b53051eca496e1f9"
      RoleArn: !GetAtt ClusterRole.Arn
      Tags:
        - Key: "created-by"
          Value: "juan.irabedra"
    DependsOn: "ClusterRole"
  Nodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: airflow-poc-cluster
      InstanceTypes:
        - "t3.medium"
      NodegroupName: "general-ng"
      ScalingConfig:
           MinSize: 3
           DesiredSize: 4
           MaxSize: 5
      NodeRole: !GetAtt NodeRole.Arn
      Subnets:
        - subnet-04e9d0c9f1940f570
        - subnet-0109e0d73006b4bc8
        - subnet-0b53051eca496e1f9
    DependsOn:
         - "Cluster"
         - "NodeRole"
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      VolumeType: gp3
      Size: 6
      Tags:
        - Key: "created-by"
          Value: "juan.irabedra"