Resources:
  AirflowPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
                - "ec2:AttachVolume"
                - "ec2:CreateSnapshot"
                - "ec2:CreateTags"
                - "ec2:CreateVolume"
                - "ec2:DeleteSnapshot"
                - "ec2:DeleteTags"
                - "ec2:DeleteVolume"
                - "ec2:DescribeAvailabilityZones"
                - "ec2:DescribeInstances"
                - "ec2:DescribeSnapshots"
                - "ec2:DescribeTags"
                - "ec2:DescribeVolumes"
                - "ec2:DescribeVolumesModifications"
                - "ec2:DetachVolume"
                - "ec2:ModifyVolume"
            Resource: '*'
      ManagedPolicyName: AirflowBatchPolicy
    DependsOn: Cluster
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: 'Provides basic EKS cluster permissions'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: airflow-poc-eks-cluster-role
  NodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: 'Provides basic EKS node permissions'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSBatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - !GetAtt AirflowPolicy.PolicyArn
      RoleName: airflow-poc-eks-node-role
    DependsOn: AirflowPolicy
  UserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - eks.amazonaws.com
                - batch.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: 'Provides EKS cluster user permissions to consume services'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSBatchFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: airflow-poc-eks-user-role
    DependsOn: "Cluster"
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: "airflow-poc-cluster"
      ResourcesVpcConfig:
        SubnetIds:
          - "subnet-09e1707aa176f8c89"
          - "subnet-027fb858b4bc37ee4"
          - "subnet-07243de5096bad62c"
          - "subnet-0a023361297003e49"
      RoleArn: !GetAtt ClusterRole.Arn
      Tags:
        - Key: "created-by"
          Value: "juan.irabedra"
    DependsOn: "ClusterRole"
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: airflow-poc-cluster
      InstanceTypes:
        - "t3.medium"
      NodegroupName: "general-ng"
      ScalingConfig:
           MinSize: 3
           DesiredSize: 4
           MaxSize: 5
      NodeRole: !GetAtt NodeRole.Arn
      Subnets:
        - subnet-09e1707aa176f8c89
        - subnet-027fb858b4bc37ee4
        - subnet-07243de5096bad62c
        - subnet-0a023361297003e49
    DependsOn:
         - "Cluster"
         - "NodeRole"
  EbsCsiDriverRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 'eks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        -  arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
        - !GetAtt AirflowPolicy.PolicyArn
      RoleName: "AirflowPocEBSCSIDriverRole"
    DependsOn: 
      - "Cluster"
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      VolumeType: gp3
      Size: 6
      Tags:
        - Key: "created-by"
          Value: "juan.irabedra"
      